# Generated by Django 3.2.6 on 2021-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
