# Generated by Django 3.2.6 on 2021-08-03 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_auth', '0002_cryptouser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptouser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
